### PR TITLE
Use terser

### LINKED ISSUE #40: Supporting uglify-es?
Hello,

What about supporting ES6, e.g. including uglify-es?

This would help using other libs that require ES6, e.g. @yaga/leaflet-ng2.

Thanks, JC

### PR DESCRIPTION
**Pull request by shvaikalesh**
Closes #40

**Tested with:**

* [x] `ostio-exim`
* [x] `ostio-chaplin`

### CODE REVIEW

**Comment by evenfrost** [comment]
It seems UglifyJS v3 doesn't support ES2015+ out of the box yet, as all the related work is on [harmony](https://github.com/mishoo/UglifyJS2/tree/harmony) branch. Is there any way to use `harmony` branch with Brunch without making raw CLI logic?

**Comment by shvaikalesh** [comment]
@evenfrost, thanks for pointing that out. Changed to `uglify-es`: it is considered stable.

**Comment by nest-aka-swan** [comment]
Without this pull request merged, babel-brunch with babel-preset-env is useless as it can produce ES6+ code which is not supported by uglify-js.

**Comment by sn3p** [comment]
Status on this?

**Pull request merged**
